### ISSUE TITLE
Plan Creator Missing Test Types

### ISSUE THREAD

**Issue by ManiSC18** [HarmanU/test-utility-app#27]
Hiya Harman, could the Test Plan Creator's test type's be updated with options for Insights and Resolve please? Been asked to send this by Mr Handford. Regards.

**Comment by HarmanU** [comment]
Hey, Sorry for the late response, i didn't receive any notifications about this issue. I have made the changes and they will be available in release 1.7.0-pre6

Let me know if there are any issues.
